/** AUTO-GENERATED by scripts/generate-install-countries.mjs */
#pragma once
#include <stddef.h>
#include <stdint.h>

struct RmsInstallCountryRow {
  const char *lookup_key;
  uint16_t nominal_v;
  uint8_t frequency_hz;
  uint8_t linky_available;
};

#define RMS_INSTALL_COUNTRY_COUNT 256

const RmsInstallCountryRow *helio_install_country_table(void);
size_t helio_install_country_table_count(void);
/** Resolve lookup key (e.g. FR, JP-W). Returns nullptr if unknown. */
const RmsInstallCountryRow *helio_install_country_find(const char *lookup_key);
