#!/usr/bin/env python3
"""
Build the Vite SPA in `web/`, gzip the resulting single-file HTML, and emit
`firmware/pageHtmlApp.h` (PROGMEM byte array) for the firmware.

Usage:
  python3 build_web.py            # full build
  python3 build_web.py --skip-npm # reuse current web/dist (CI / fast loop)

Hooked into PlatformIO via `extra_scripts = pre:build_web.py` so that
`pio run` always rebuilds before compiling the firmware.
"""
from __future__ import annotations

import argparse
import gzip
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

if "__file__" in globals():
    REPO = Path(__file__).resolve().parent
else:
    # PlatformIO/SCons can execute extra_scripts without defining __file__.
    REPO = Path(os.environ.get("PROJECT_DIR", os.getcwd())).resolve()
WEB = REPO / "web"
DIST = WEB / "dist"
HEADER = REPO / "firmware" / "pageHtmlApp.h"
PWA_HEADER = REPO / "firmware" / "pageHtmlPwaAssets.h"
SOFT_LIMIT = 200 * 1024  # warn above 200 KB gzipped

SKIP_KEYS = {"PIOENV", "PIOFRAMEWORK", "PROJECT_DIR"}


def is_pio_invocation() -> bool:
    """True when invoked by PlatformIO's pre-script hook (Env.AddPreAction)."""
    return any(k in os.environ for k in SKIP_KEYS) and "SCons" in sys.modules


def newest_mtime(root: Path, *patterns: str) -> float:
    latest = 0.0
    for pat in patterns:
        for p in root.rglob(pat):
            if "node_modules" in p.parts or "dist" in p.parts:
                continue
            try:
                latest = max(latest, p.stat().st_mtime)
            except OSError:
                continue
    return latest


def needs_rebuild() -> bool:
    if not HEADER.exists() or not PWA_HEADER.exists():
        return True
    header_m = min(HEADER.stat().st_mtime, PWA_HEADER.stat().st_mtime)
    src_m = newest_mtime(
        WEB,
        "*.ts",
        "*.css",
        "*.html",
        "*.json",
        "*.mjs",
        "*.webmanifest",
        "*.js",
        "*.png",
        "*.svg",
    )
    return src_m > header_m


def run(cmd: list[str], cwd: Path, *, env: dict[str, str] | None = None) -> None:
    print("$", " ".join(cmd), "  (cwd=", cwd, ")", sep="")
    merged = os.environ.copy()
    if env:
        merged.update(env)
    subprocess.run(cmd, cwd=cwd, check=True, env=merged)


def ensure_node_modules(skip_npm: bool) -> None:
    if skip_npm:
        return
    nm = WEB / "node_modules"
    pkg_lock = WEB / "package-lock.json"
    fresh = nm.exists() and pkg_lock.exists() and nm.stat().st_mtime >= pkg_lock.stat().st_mtime
    if fresh:
        return
    if shutil.which("npm") is None:
        sys.exit("build_web: npm is required (install Node.js or run with --skip-npm if dist exists)")
    if pkg_lock.exists():
        run(["npm", "ci"], cwd=WEB)
    else:
        run(["npm", "install"], cwd=WEB)


def _pioenv_name() -> str:
    """PlatformIO pre-scripts expose PIOENV on the SCons env, not always in os.environ."""
    if "SCons" in sys.modules:
        try:
            Import = __import__("SCons.Script", fromlist=["Import"]).Import
            Import("env")
            return env.subst("$PIOENV").strip()  # type: ignore[name-defined]
        except Exception:
            pass
    return os.environ.get("PIOENV", "").strip()


def resolve_firmware_version() -> str:
    """Match extra_scripts/set_firmware_version.py (see scripts/firmware_version_resolve.py)."""
    sys.path.insert(0, str(REPO / "scripts"))
    from firmware_version_resolve import resolve_for_build

    return resolve_for_build(_pioenv_name())


def vite_build(skip_npm: bool) -> None:
    if skip_npm:
        return
    if shutil.which("npm") is None:
        sys.exit("build_web: npm is required for vite build")
    fw_version = resolve_firmware_version()
    print(f"build_web: VITE_FIRMWARE_VERSION={fw_version}")
    docs_origin = os.environ.get(
        "VITE_DOCS_SITE_ORIGIN", "https://heliozero.clouded.fr"
    ).rstrip("/")
    print(f"build_web: VITE_DOCS_SITE_ORIGIN={docs_origin}")
    run(
        ["npm", "run", "build:firmware"],
        cwd=WEB,
        env={
            "VITE_FIRMWARE_BUNDLE": "1",
            "VITE_FIRMWARE_VERSION": fw_version,
            "VITE_DOCS_SITE_ORIGIN": docs_origin,
        },
    )


def emit_header(html_bytes: bytes) -> bytes:
    gz = gzip.compress(html_bytes, compresslevel=9, mtime=0)
    rows: list[str] = []
    for i, b in enumerate(gz):
        if i % 16 == 0:
            rows.append("\n  ")
        rows.append(f"0x{b:02x}, ")
    body = "".join(rows).rstrip().rstrip(",")
    text = f"""// AUTO-GENERATED by build_web.py — do not edit.
// Single-file SPA bundle (gzipped) served by the firmware web server.
// Source: web/dist/index.html
// Decompressed size: {len(html_bytes)} bytes
// Compressed size:   {len(gz)} bytes
#pragma once
#include <Arduino.h>

const uint8_t MainAppGz[] PROGMEM = {{{body}
}};
const size_t MainAppGzLen = {len(gz)};
const size_t MainAppRawLen = {len(html_bytes)};
"""
    HEADER.write_text(text, encoding="utf-8")
    return gz


def _format_progmem_rows(data: bytes) -> str:
    rows: list[str] = []
    for i, b in enumerate(data):
        if i % 16 == 0:
            rows.append("\n  ")
        rows.append(f"0x{b:02x}, ")
    return "".join(rows).rstrip().rstrip(",")


def emit_pwa_assets_header(fw_version: str) -> None:
    """Embed manifest, icons, and service worker from web/dist for firmware routes."""
    manifest_path = DIST / "manifest.webmanifest"
    icon192_path = DIST / "pwa" / "icon-192.png"
    icon512_path = DIST / "pwa" / "icon-512.png"
    sw_path = DIST / "sw.js"
    for path in (manifest_path, icon192_path, icon512_path, sw_path):
        if not path.exists():
            sys.exit(f"build_web: missing PWA asset {path.relative_to(REPO)} — run npm run sync:brand")

    manifest_bytes = manifest_path.read_bytes()
    icon192 = icon192_path.read_bytes()
    icon512 = icon512_path.read_bytes()
    sw_bytes = sw_path.read_text(encoding="utf-8").replace("__HELIO_UI_VERSION__", fw_version).encode("utf-8")

    sections = [
        (
            "PwaManifestJson",
            "char",
            manifest_bytes,
            "Web app manifest (application/manifest+json)",
        ),
        ("PwaIcon192", "uint8_t", icon192, "PWA icon 192x192 PNG"),
        ("PwaIcon512", "uint8_t", icon512, "PWA icon 512x512 PNG"),
        ("PwaSwJs", "char", sw_bytes, "Service worker (application/javascript)"),
    ]

    parts = [
        "// AUTO-GENERATED by build_web.py — do not edit.",
        "// PWA assets served at /manifest.webmanifest, /pwa/icon-*.png, /sw.js",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    for var_name, c_type, payload, comment in sections:
        body = _format_progmem_rows(payload)
        parts.append(f"// {comment}")
        parts.append(f"const {c_type} {var_name}[] PROGMEM = {{{body}")
        parts.append("};")
        parts.append(f"const size_t {var_name}Len = {len(payload)};")
        parts.append("")

    PWA_HEADER.write_text("\n".join(parts), encoding="utf-8")
    print(
        f"build_web: {PWA_HEADER.name} manifest={len(manifest_bytes)} "
        f"icon192={len(icon192)} icon512={len(icon512)} sw={len(sw_bytes)} bytes"
    )


def cli() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-npm",
        action="store_true",
        help="reuse existing web/dist/index.html (do not run npm)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="rebuild even if pageHtmlApp.h is newer than web sources",
    )
    args = parser.parse_args()

    if not args.force and not args.skip_npm and not needs_rebuild():
        print("build_web: pageHtmlApp.h is up to date, nothing to do (use --force to rebuild)")
        return

    if not args.skip_npm:
        ensure_node_modules(skip_npm=False)
        vite_build(skip_npm=False)

    out = DIST / "index.html"
    if not out.exists():
        sys.exit(f"build_web: missing {out.relative_to(REPO)} — Vite build failed?")
    html_bytes = out.read_bytes()
    gz = emit_header(html_bytes)
    emit_pwa_assets_header(resolve_firmware_version())

    pct = 100.0 * len(gz) / max(1, len(html_bytes))
    print(
        f"build_web: {HEADER.name} {len(gz)} bytes gz "
        f"({len(html_bytes)} raw, {pct:.1f}%)"
    )
    if len(gz) > SOFT_LIMIT:
        print(
            f"warning: gzipped bundle exceeds soft limit ({SOFT_LIMIT // 1024} KB)",
            file=sys.stderr,
        )


def main() -> None:
    if is_pio_invocation():
        # PlatformIO hands us its `Import` env. We just want to run the build
        # before sources compile; do it once and return without affecting SCons.
        try:
            cli()
        except subprocess.CalledProcessError as e:
            sys.exit(f"build_web: subprocess failed ({e})")
        return
    cli()


if __name__ == "__main__":
    main()
elif "SCons" in sys.modules:
    # PlatformIO pre:script — runs at script load time.
    try:
        cli_argv = []  # PIO does not pass argv; rely on default behaviour
        sys.argv = [sys.argv[0]] + cli_argv
        cli()
    except SystemExit:
        raise
    except Exception as e:  # noqa: BLE001
        print(f"build_web: error during PIO pre-script: {e}", file=sys.stderr)
