/** AUTO-GENERATED by scripts/generate-install-countries.mjs — do not edit */
export type MainsFrequencyHz = 50 | 60;

export interface InstallCountryVariant {
  variantId: string;
  lookupKey: string;
  defaultNominalV: number;
  defaultFrequencyHz: MainsFrequencyHz;
  suggestedTimeTz?: string;
}

export interface InstallCountry {
  iso2: string;
  lookupKey: string;
  defaultNominalV: number;
  defaultFrequencyHz: MainsFrequencyHz;
  suggestedTimeTz?: string;
  linkyAvailable?: boolean;
  splitNoteKey?: string;
  splitVariants?: InstallCountryVariant[];
}

export const INSTALL_COUNTRIES: InstallCountry[] = [
  {
    "iso2": "AD",
    "lookupKey": "AD",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Andorra"
  },
  {
    "iso2": "AE",
    "lookupKey": "AE",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Dubai"
  },
  {
    "iso2": "AF",
    "lookupKey": "AF",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Kabul"
  },
  {
    "iso2": "AG",
    "lookupKey": "AG",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Antigua"
  },
  {
    "iso2": "AI",
    "lookupKey": "AI",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Anguilla"
  },
  {
    "iso2": "AL",
    "lookupKey": "AL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Tirane"
  },
  {
    "iso2": "AM",
    "lookupKey": "AM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Yerevan"
  },
  {
    "iso2": "AO",
    "lookupKey": "AO",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Luanda"
  },
  {
    "iso2": "AR",
    "lookupKey": "AR",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Argentina/Buenos_Aires"
  },
  {
    "iso2": "AS",
    "lookupKey": "AS",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Pago_Pago"
  },
  {
    "iso2": "AT",
    "lookupKey": "AT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Vienna"
  },
  {
    "iso2": "AU",
    "lookupKey": "AU",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Australia/Sydney"
  },
  {
    "iso2": "AW",
    "lookupKey": "AW",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Aruba"
  },
  {
    "iso2": "AX",
    "lookupKey": "AX",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Mariehamn"
  },
  {
    "iso2": "AZ",
    "lookupKey": "AZ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Baku"
  },
  {
    "iso2": "BA",
    "lookupKey": "BA",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Sarajevo"
  },
  {
    "iso2": "BB",
    "lookupKey": "BB",
    "defaultNominalV": 115,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Barbados"
  },
  {
    "iso2": "BD",
    "lookupKey": "BD",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Dhaka"
  },
  {
    "iso2": "BE",
    "lookupKey": "BE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Brussels"
  },
  {
    "iso2": "BF",
    "lookupKey": "BF",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Ouagadougou"
  },
  {
    "iso2": "BG",
    "lookupKey": "BG",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Sofia"
  },
  {
    "iso2": "BH",
    "lookupKey": "BH",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Bahrain"
  },
  {
    "iso2": "BI",
    "lookupKey": "BI",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Bujumbura"
  },
  {
    "iso2": "BJ",
    "lookupKey": "BJ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Porto-Novo"
  },
  {
    "iso2": "BL",
    "lookupKey": "BL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/St_Barthelemy"
  },
  {
    "iso2": "BM",
    "lookupKey": "BM",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Atlantic/Bermuda"
  },
  {
    "iso2": "BN",
    "lookupKey": "BN",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Brunei"
  },
  {
    "iso2": "BO",
    "lookupKey": "BO",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/La_Paz"
  },
  {
    "iso2": "BQ",
    "lookupKey": "BQ",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Kralendijk"
  },
  {
    "iso2": "BR",
    "lookupKey": "BR",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Sao_Paulo",
    "splitNoteKey": "settings.countrySplitBrazil",
    "splitVariants": [
      {
        "variantId": "127",
        "lookupKey": "BR-127",
        "defaultNominalV": 127,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "America/Sao_Paulo"
      },
      {
        "variantId": "220",
        "lookupKey": "BR-220",
        "defaultNominalV": 220,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "America/Sao_Paulo"
      }
    ]
  },
  {
    "iso2": "BS",
    "lookupKey": "BS",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Nassau"
  },
  {
    "iso2": "BT",
    "lookupKey": "BT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Thimphu"
  },
  {
    "iso2": "BW",
    "lookupKey": "BW",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Gaborone"
  },
  {
    "iso2": "BY",
    "lookupKey": "BY",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Minsk"
  },
  {
    "iso2": "BZ",
    "lookupKey": "BZ",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Belize",
    "splitNoteKey": "settings.countrySplitBelize",
    "splitVariants": [
      {
        "variantId": "110",
        "lookupKey": "BZ-110",
        "defaultNominalV": 110,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "America/Belize"
      },
      {
        "variantId": "220",
        "lookupKey": "BZ-220",
        "defaultNominalV": 220,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "America/Belize"
      }
    ]
  },
  {
    "iso2": "CA",
    "lookupKey": "CA",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Toronto"
  },
  {
    "iso2": "CC",
    "lookupKey": "CC",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Cocos"
  },
  {
    "iso2": "CD",
    "lookupKey": "CD",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Kinshasa"
  },
  {
    "iso2": "CF",
    "lookupKey": "CF",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Bangui"
  },
  {
    "iso2": "CG",
    "lookupKey": "CG",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Brazzaville"
  },
  {
    "iso2": "CH",
    "lookupKey": "CH",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Zurich"
  },
  {
    "iso2": "CI",
    "lookupKey": "CI",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Abidjan"
  },
  {
    "iso2": "CK",
    "lookupKey": "CK",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Rarotonga"
  },
  {
    "iso2": "CL",
    "lookupKey": "CL",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Santiago"
  },
  {
    "iso2": "CM",
    "lookupKey": "CM",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Douala"
  },
  {
    "iso2": "CN",
    "lookupKey": "CN",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Shanghai"
  },
  {
    "iso2": "CO",
    "lookupKey": "CO",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Bogota"
  },
  {
    "iso2": "CR",
    "lookupKey": "CR",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Costa_Rica"
  },
  {
    "iso2": "CU",
    "lookupKey": "CU",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Havana"
  },
  {
    "iso2": "CV",
    "lookupKey": "CV",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Atlantic/Cape_Verde"
  },
  {
    "iso2": "CW",
    "lookupKey": "CW",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Curacao"
  },
  {
    "iso2": "CX",
    "lookupKey": "CX",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Christmas"
  },
  {
    "iso2": "CY",
    "lookupKey": "CY",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Nicosia"
  },
  {
    "iso2": "CZ",
    "lookupKey": "CZ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Prague"
  },
  {
    "iso2": "DE",
    "lookupKey": "DE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Berlin"
  },
  {
    "iso2": "DJ",
    "lookupKey": "DJ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Djibouti"
  },
  {
    "iso2": "DK",
    "lookupKey": "DK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Copenhagen"
  },
  {
    "iso2": "DM",
    "lookupKey": "DM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Dominica"
  },
  {
    "iso2": "DO",
    "lookupKey": "DO",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Santo_Domingo"
  },
  {
    "iso2": "DZ",
    "lookupKey": "DZ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Algiers"
  },
  {
    "iso2": "EC",
    "lookupKey": "EC",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Guayaquil"
  },
  {
    "iso2": "EE",
    "lookupKey": "EE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Tallinn"
  },
  {
    "iso2": "EG",
    "lookupKey": "EG",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Cairo"
  },
  {
    "iso2": "EH",
    "lookupKey": "EH",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/El_Aaiun"
  },
  {
    "iso2": "ER",
    "lookupKey": "ER",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Asmara"
  },
  {
    "iso2": "ES",
    "lookupKey": "ES",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Madrid"
  },
  {
    "iso2": "ET",
    "lookupKey": "ET",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Addis_Ababa"
  },
  {
    "iso2": "FI",
    "lookupKey": "FI",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Helsinki"
  },
  {
    "iso2": "FJ",
    "lookupKey": "FJ",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Fiji"
  },
  {
    "iso2": "FK",
    "lookupKey": "FK",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Atlantic/Stanley"
  },
  {
    "iso2": "FM",
    "lookupKey": "FM",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Chuuk"
  },
  {
    "iso2": "FO",
    "lookupKey": "FO",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Atlantic/Faroe"
  },
  {
    "iso2": "FR",
    "lookupKey": "FR",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Paris",
    "linkyAvailable": true
  },
  {
    "iso2": "GA",
    "lookupKey": "GA",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Libreville"
  },
  {
    "iso2": "GB",
    "lookupKey": "GB",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/London"
  },
  {
    "iso2": "GD",
    "lookupKey": "GD",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Grenada"
  },
  {
    "iso2": "GE",
    "lookupKey": "GE",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Tbilisi"
  },
  {
    "iso2": "GF",
    "lookupKey": "GF",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Cayenne"
  },
  {
    "iso2": "GG",
    "lookupKey": "GG",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Guernsey"
  },
  {
    "iso2": "GH",
    "lookupKey": "GH",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Accra"
  },
  {
    "iso2": "GI",
    "lookupKey": "GI",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Gibraltar"
  },
  {
    "iso2": "GL",
    "lookupKey": "GL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Godthab"
  },
  {
    "iso2": "GM",
    "lookupKey": "GM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Banjul"
  },
  {
    "iso2": "GN",
    "lookupKey": "GN",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Conakry"
  },
  {
    "iso2": "GP",
    "lookupKey": "GP",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Guadeloupe"
  },
  {
    "iso2": "GQ",
    "lookupKey": "GQ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Malabo"
  },
  {
    "iso2": "GR",
    "lookupKey": "GR",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Athens"
  },
  {
    "iso2": "GT",
    "lookupKey": "GT",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Guatemala"
  },
  {
    "iso2": "GU",
    "lookupKey": "GU",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Guam"
  },
  {
    "iso2": "GW",
    "lookupKey": "GW",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Bissau"
  },
  {
    "iso2": "GY",
    "lookupKey": "GY",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Guyana"
  },
  {
    "iso2": "HK",
    "lookupKey": "HK",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Hong_Kong"
  },
  {
    "iso2": "HN",
    "lookupKey": "HN",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Tegucigalpa"
  },
  {
    "iso2": "HR",
    "lookupKey": "HR",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Zagreb"
  },
  {
    "iso2": "HT",
    "lookupKey": "HT",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Port-au-Prince"
  },
  {
    "iso2": "HU",
    "lookupKey": "HU",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Budapest"
  },
  {
    "iso2": "ID",
    "lookupKey": "ID",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Jakarta"
  },
  {
    "iso2": "IE",
    "lookupKey": "IE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Dublin"
  },
  {
    "iso2": "IL",
    "lookupKey": "IL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Jerusalem"
  },
  {
    "iso2": "IM",
    "lookupKey": "IM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Isle_of_Man"
  },
  {
    "iso2": "IN",
    "lookupKey": "IN",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Kolkata"
  },
  {
    "iso2": "IO",
    "lookupKey": "IO",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Chagos"
  },
  {
    "iso2": "IQ",
    "lookupKey": "IQ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Baghdad"
  },
  {
    "iso2": "IR",
    "lookupKey": "IR",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Tehran"
  },
  {
    "iso2": "IS",
    "lookupKey": "IS",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Atlantic/Reykjavik"
  },
  {
    "iso2": "IT",
    "lookupKey": "IT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Rome"
  },
  {
    "iso2": "JE",
    "lookupKey": "JE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Jersey"
  },
  {
    "iso2": "JM",
    "lookupKey": "JM",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Jamaica"
  },
  {
    "iso2": "JO",
    "lookupKey": "JO",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Amman"
  },
  {
    "iso2": "JP",
    "lookupKey": "JP",
    "defaultNominalV": 100,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Tokyo",
    "splitNoteKey": "settings.countrySplitJapan",
    "splitVariants": [
      {
        "variantId": "E",
        "lookupKey": "JP-E",
        "defaultNominalV": 100,
        "defaultFrequencyHz": 50,
        "suggestedTimeTz": "Asia/Tokyo"
      },
      {
        "variantId": "W",
        "lookupKey": "JP-W",
        "defaultNominalV": 100,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "Asia/Tokyo"
      }
    ]
  },
  {
    "iso2": "KE",
    "lookupKey": "KE",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Nairobi"
  },
  {
    "iso2": "KG",
    "lookupKey": "KG",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Bishkek"
  },
  {
    "iso2": "KH",
    "lookupKey": "KH",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Phnom_Penh"
  },
  {
    "iso2": "KI",
    "lookupKey": "KI",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Tarawa"
  },
  {
    "iso2": "KM",
    "lookupKey": "KM",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Comoro"
  },
  {
    "iso2": "KN",
    "lookupKey": "KN",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/St_Kitts"
  },
  {
    "iso2": "KP",
    "lookupKey": "KP",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Pyongyang"
  },
  {
    "iso2": "KR",
    "lookupKey": "KR",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Asia/Seoul"
  },
  {
    "iso2": "KW",
    "lookupKey": "KW",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Kuwait"
  },
  {
    "iso2": "KY",
    "lookupKey": "KY",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Cayman"
  },
  {
    "iso2": "KZ",
    "lookupKey": "KZ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Almaty"
  },
  {
    "iso2": "LA",
    "lookupKey": "LA",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Vientiane"
  },
  {
    "iso2": "LB",
    "lookupKey": "LB",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Beirut"
  },
  {
    "iso2": "LC",
    "lookupKey": "LC",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/St_Lucia"
  },
  {
    "iso2": "LI",
    "lookupKey": "LI",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Vaduz"
  },
  {
    "iso2": "LK",
    "lookupKey": "LK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Colombo"
  },
  {
    "iso2": "LR",
    "lookupKey": "LR",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Africa/Monrovia"
  },
  {
    "iso2": "LS",
    "lookupKey": "LS",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Maseru"
  },
  {
    "iso2": "LT",
    "lookupKey": "LT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Vilnius"
  },
  {
    "iso2": "LU",
    "lookupKey": "LU",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Luxembourg"
  },
  {
    "iso2": "LV",
    "lookupKey": "LV",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Riga"
  },
  {
    "iso2": "LY",
    "lookupKey": "LY",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Tripoli"
  },
  {
    "iso2": "MA",
    "lookupKey": "MA",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Casablanca"
  },
  {
    "iso2": "MC",
    "lookupKey": "MC",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Monaco"
  },
  {
    "iso2": "MD",
    "lookupKey": "MD",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Chisinau"
  },
  {
    "iso2": "ME",
    "lookupKey": "ME",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Podgorica"
  },
  {
    "iso2": "MF",
    "lookupKey": "MF",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Marigot"
  },
  {
    "iso2": "MG",
    "lookupKey": "MG",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Antananarivo",
    "splitNoteKey": "settings.countrySplitMadagascar",
    "splitVariants": [
      {
        "variantId": "127",
        "lookupKey": "MG-127",
        "defaultNominalV": 127,
        "defaultFrequencyHz": 50,
        "suggestedTimeTz": "Indian/Antananarivo"
      },
      {
        "variantId": "220",
        "lookupKey": "MG-220",
        "defaultNominalV": 220,
        "defaultFrequencyHz": 50,
        "suggestedTimeTz": "Indian/Antananarivo"
      }
    ]
  },
  {
    "iso2": "MH",
    "lookupKey": "MH",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Majuro"
  },
  {
    "iso2": "MK",
    "lookupKey": "MK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Skopje"
  },
  {
    "iso2": "ML",
    "lookupKey": "ML",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Bamako"
  },
  {
    "iso2": "MM",
    "lookupKey": "MM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Yangon"
  },
  {
    "iso2": "MN",
    "lookupKey": "MN",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Ulaanbaatar"
  },
  {
    "iso2": "MO",
    "lookupKey": "MO",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Macau"
  },
  {
    "iso2": "MP",
    "lookupKey": "MP",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Saipan"
  },
  {
    "iso2": "MQ",
    "lookupKey": "MQ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Martinique"
  },
  {
    "iso2": "MR",
    "lookupKey": "MR",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Nouakchott"
  },
  {
    "iso2": "MS",
    "lookupKey": "MS",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Montserrat"
  },
  {
    "iso2": "MT",
    "lookupKey": "MT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Malta"
  },
  {
    "iso2": "MU",
    "lookupKey": "MU",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Mauritius"
  },
  {
    "iso2": "MV",
    "lookupKey": "MV",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Maldives"
  },
  {
    "iso2": "MW",
    "lookupKey": "MW",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Blantyre"
  },
  {
    "iso2": "MX",
    "lookupKey": "MX",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Mexico_City"
  },
  {
    "iso2": "MY",
    "lookupKey": "MY",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Kuala_Lumpur"
  },
  {
    "iso2": "MZ",
    "lookupKey": "MZ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Maputo"
  },
  {
    "iso2": "NA",
    "lookupKey": "NA",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Windhoek"
  },
  {
    "iso2": "NC",
    "lookupKey": "NC",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Noumea"
  },
  {
    "iso2": "NE",
    "lookupKey": "NE",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Niamey"
  },
  {
    "iso2": "NF",
    "lookupKey": "NF",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Norfolk"
  },
  {
    "iso2": "NG",
    "lookupKey": "NG",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Lagos"
  },
  {
    "iso2": "NI",
    "lookupKey": "NI",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Managua"
  },
  {
    "iso2": "NL",
    "lookupKey": "NL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Amsterdam"
  },
  {
    "iso2": "NO",
    "lookupKey": "NO",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Oslo"
  },
  {
    "iso2": "NP",
    "lookupKey": "NP",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Kathmandu"
  },
  {
    "iso2": "NR",
    "lookupKey": "NR",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Nauru"
  },
  {
    "iso2": "NU",
    "lookupKey": "NU",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Niue"
  },
  {
    "iso2": "NZ",
    "lookupKey": "NZ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Auckland"
  },
  {
    "iso2": "OM",
    "lookupKey": "OM",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Muscat"
  },
  {
    "iso2": "PA",
    "lookupKey": "PA",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Panama"
  },
  {
    "iso2": "PE",
    "lookupKey": "PE",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Lima"
  },
  {
    "iso2": "PF",
    "lookupKey": "PF",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Tahiti"
  },
  {
    "iso2": "PG",
    "lookupKey": "PG",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Port_Moresby"
  },
  {
    "iso2": "PH",
    "lookupKey": "PH",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Asia/Manila"
  },
  {
    "iso2": "PK",
    "lookupKey": "PK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Karachi"
  },
  {
    "iso2": "PL",
    "lookupKey": "PL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Warsaw"
  },
  {
    "iso2": "PM",
    "lookupKey": "PM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Miquelon"
  },
  {
    "iso2": "PN",
    "lookupKey": "PN",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Pitcairn"
  },
  {
    "iso2": "PR",
    "lookupKey": "PR",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Puerto_Rico"
  },
  {
    "iso2": "PS",
    "lookupKey": "PS",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Gaza"
  },
  {
    "iso2": "PT",
    "lookupKey": "PT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Lisbon"
  },
  {
    "iso2": "PW",
    "lookupKey": "PW",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Palau"
  },
  {
    "iso2": "PY",
    "lookupKey": "PY",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Asuncion"
  },
  {
    "iso2": "QA",
    "lookupKey": "QA",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Qatar"
  },
  {
    "iso2": "RE",
    "lookupKey": "RE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Reunion"
  },
  {
    "iso2": "RO",
    "lookupKey": "RO",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Bucharest"
  },
  {
    "iso2": "RS",
    "lookupKey": "RS",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Belgrade"
  },
  {
    "iso2": "RU",
    "lookupKey": "RU",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Moscow"
  },
  {
    "iso2": "RW",
    "lookupKey": "RW",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Kigali"
  },
  {
    "iso2": "SA",
    "lookupKey": "SA",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Asia/Riyadh",
    "splitNoteKey": "settings.countrySplitSaudi",
    "splitVariants": [
      {
        "variantId": "127",
        "lookupKey": "SA-127",
        "defaultNominalV": 127,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "Asia/Riyadh"
      },
      {
        "variantId": "220",
        "lookupKey": "SA-220",
        "defaultNominalV": 220,
        "defaultFrequencyHz": 60,
        "suggestedTimeTz": "Asia/Riyadh"
      }
    ]
  },
  {
    "iso2": "SB",
    "lookupKey": "SB",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Guadalcanal"
  },
  {
    "iso2": "SC",
    "lookupKey": "SC",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Mahe"
  },
  {
    "iso2": "SD",
    "lookupKey": "SD",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Khartoum"
  },
  {
    "iso2": "SE",
    "lookupKey": "SE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Stockholm"
  },
  {
    "iso2": "SG",
    "lookupKey": "SG",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Singapore"
  },
  {
    "iso2": "SH",
    "lookupKey": "SH",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Atlantic/St_Helena"
  },
  {
    "iso2": "SI",
    "lookupKey": "SI",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Ljubljana"
  },
  {
    "iso2": "SJ",
    "lookupKey": "SJ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Arctic/Longyearbyen"
  },
  {
    "iso2": "SK",
    "lookupKey": "SK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Bratislava"
  },
  {
    "iso2": "SL",
    "lookupKey": "SL",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Freetown"
  },
  {
    "iso2": "SM",
    "lookupKey": "SM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/San_Marino"
  },
  {
    "iso2": "SN",
    "lookupKey": "SN",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Dakar"
  },
  {
    "iso2": "SO",
    "lookupKey": "SO",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Mogadishu"
  },
  {
    "iso2": "SR",
    "lookupKey": "SR",
    "defaultNominalV": 127,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Paramaribo"
  },
  {
    "iso2": "SS",
    "lookupKey": "SS",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Juba"
  },
  {
    "iso2": "ST",
    "lookupKey": "ST",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Sao_Tome"
  },
  {
    "iso2": "SV",
    "lookupKey": "SV",
    "defaultNominalV": 115,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/El_Salvador"
  },
  {
    "iso2": "SX",
    "lookupKey": "SX",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Lower_Princes"
  },
  {
    "iso2": "SY",
    "lookupKey": "SY",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Damascus"
  },
  {
    "iso2": "SZ",
    "lookupKey": "SZ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Mbabane"
  },
  {
    "iso2": "TC",
    "lookupKey": "TC",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Grand_Turk"
  },
  {
    "iso2": "TD",
    "lookupKey": "TD",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Ndjamena"
  },
  {
    "iso2": "TG",
    "lookupKey": "TG",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Lome"
  },
  {
    "iso2": "TH",
    "lookupKey": "TH",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Bangkok"
  },
  {
    "iso2": "TJ",
    "lookupKey": "TJ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Dushanbe"
  },
  {
    "iso2": "TK",
    "lookupKey": "TK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Fakaofo"
  },
  {
    "iso2": "TL",
    "lookupKey": "TL",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Dili"
  },
  {
    "iso2": "TM",
    "lookupKey": "TM",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Ashgabat"
  },
  {
    "iso2": "TN",
    "lookupKey": "TN",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Tunis"
  },
  {
    "iso2": "TO",
    "lookupKey": "TO",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Tongatapu"
  },
  {
    "iso2": "TR",
    "lookupKey": "TR",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Istanbul"
  },
  {
    "iso2": "TT",
    "lookupKey": "TT",
    "defaultNominalV": 115,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Port_of_Spain"
  },
  {
    "iso2": "TV",
    "lookupKey": "TV",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Funafuti"
  },
  {
    "iso2": "TW",
    "lookupKey": "TW",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Asia/Taipei"
  },
  {
    "iso2": "TZ",
    "lookupKey": "TZ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Dar_es_Salaam"
  },
  {
    "iso2": "UA",
    "lookupKey": "UA",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Kyiv"
  },
  {
    "iso2": "UG",
    "lookupKey": "UG",
    "defaultNominalV": 240,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Kampala"
  },
  {
    "iso2": "UM",
    "lookupKey": "UM",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "Pacific/Midway"
  },
  {
    "iso2": "US",
    "lookupKey": "US",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/New_York"
  },
  {
    "iso2": "UY",
    "lookupKey": "UY",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/Montevideo"
  },
  {
    "iso2": "UZ",
    "lookupKey": "UZ",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Tashkent"
  },
  {
    "iso2": "VA",
    "lookupKey": "VA",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Vatican"
  },
  {
    "iso2": "VC",
    "lookupKey": "VC",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "America/St_Vincent"
  },
  {
    "iso2": "VE",
    "lookupKey": "VE",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Caracas"
  },
  {
    "iso2": "VG",
    "lookupKey": "VG",
    "defaultNominalV": 110,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/Tortola"
  },
  {
    "iso2": "VI",
    "lookupKey": "VI",
    "defaultNominalV": 120,
    "defaultFrequencyHz": 60,
    "suggestedTimeTz": "America/St_Thomas"
  },
  {
    "iso2": "VN",
    "lookupKey": "VN",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Ho_Chi_Minh"
  },
  {
    "iso2": "VU",
    "lookupKey": "VU",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Efate"
  },
  {
    "iso2": "WF",
    "lookupKey": "WF",
    "defaultNominalV": 220,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Wallis"
  },
  {
    "iso2": "WS",
    "lookupKey": "WS",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Pacific/Apia"
  },
  {
    "iso2": "XK",
    "lookupKey": "XK",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Europe/Belgrade"
  },
  {
    "iso2": "YE",
    "lookupKey": "YE",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Asia/Aden"
  },
  {
    "iso2": "YT",
    "lookupKey": "YT",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Indian/Mayotte"
  },
  {
    "iso2": "ZA",
    "lookupKey": "ZA",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Johannesburg"
  },
  {
    "iso2": "ZM",
    "lookupKey": "ZM",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Lusaka"
  },
  {
    "iso2": "ZW",
    "lookupKey": "ZW",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "suggestedTimeTz": "Africa/Harare"
  },
  {
    "iso2": "ZZ",
    "lookupKey": "ZZ",
    "defaultNominalV": 230,
    "defaultFrequencyHz": 50,
    "splitNoteKey": "settings.countryCustom"
  }
];

export type InstallCountryLookupRow = {
  lookupKey: string;
  defaultNominalV: number;
  defaultFrequencyHz: MainsFrequencyHz;
  suggestedTimeTz?: string;
  linkyAvailable?: boolean;
};

function lookupKeyExists(key: string): boolean {
  for (const c of INSTALL_COUNTRIES) {
    if (c.lookupKey === key) return true;
    if (c.splitVariants?.some((v) => v.lookupKey === key)) return true;
  }
  return false;
}

export function resolveInstallLookupKey(
  country: string,
  variant?: string,
): string {
  const c = (country || "").trim().toUpperCase();
  if (!c || c === "ZZ") return "ZZ";
  const v = (variant || "").trim();
  if (v) {
    const full = v.includes("-") ? v.toUpperCase() : `${c}-${v.toUpperCase()}`;
    if (lookupKeyExists(full)) return full;
  }
  return c;
}

export function lookupInstallCountry(
  country: string,
  variant?: string,
): InstallCountryLookupRow | undefined {
  const key = resolveInstallLookupKey(country, variant);
  for (const c of INSTALL_COUNTRIES) {
    if (c.splitVariants) {
      const sv = c.splitVariants.find((v) => v.lookupKey === key);
      if (sv) {
        return {
          lookupKey: sv.lookupKey,
          defaultNominalV: sv.defaultNominalV,
          defaultFrequencyHz: sv.defaultFrequencyHz,
          suggestedTimeTz: sv.suggestedTimeTz,
        };
      }
    }
    if (c.lookupKey === key) {
      return {
        lookupKey: c.lookupKey,
        defaultNominalV: c.defaultNominalV,
        defaultFrequencyHz: c.defaultFrequencyHz,
        suggestedTimeTz: c.suggestedTimeTz,
        linkyAvailable: c.linkyAvailable,
      };
    }
  }
  return undefined;
}

export function countryDisplayName(iso2: string, locale: string): string {
  try {
    const dn = new Intl.DisplayNames([locale], { type: "region" });
    return dn.of(iso2) ?? iso2;
  } catch {
    return iso2;
  }
}
